[package]
name = "photomatcher-id"
version = "1.0.0"
description = "School Student Photo & Excel Matcher Suite"
authors = ["AM-Lab"]
license = "MIT"
repository = "https://github.com/duckimp/PhotoMatcher.id"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-opener = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
